% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Apr-2021 18:59:26
%  MATLAB version: 9.9.0.1538559 (R2020b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('DataSource.mat');

dt = 0.0009765625;

stillBall = saveVarsMat.stillBall; % <512x512x3 double> too many elements

clear saveVarsMat;
